# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mano Vaikinas Veganas
subtitle: 
name: # Author name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manovaikinasveganas.lt" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
repository: "manovaikinasveganas/tinklarastis"
#logo: "/pav/icon.jpg"
breadcrumbs: true  # disabled by default

# Build settings
# theme: minima
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
remote_theme: mmistakes/minimal-mistakes
# remote_theme: mmistakes/so-simple-theme
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

locale: "lt-LT"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _receptai
  - scope:
      path: ""
      type: receptai
    values:
      layout: single
      author_profile: true
      share: true
      related: true


date_format: "%Y-%m-%d"

atom_feed:
  hide: true

author:
  name     : "Arina"
  avatar   : "/pav/avatar.jpg"
  bio      : "Tinklaraštininkė ir augalinių receptų kūrėja."
  location : "Vilnius, LT"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/ManoVaikinasVeganas"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/mano_vaikinas_veganas/"
    - label: "Pakuotė po pakuotės"
      icon: "fas fa-fw fa-link"
      url: "https://popakuotės.lt"

timezone: Europe/Vilnius

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/ManoVaikinasVeganas"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/mano_vaikinas_veganas/"
    - label: "Atrask tvarius produktus"
      icon: "fas fa-fw fa-link"
      url: "https://popakuotės.lt"

search: true
lunr:
  search_within_pages: true
facebook:
  #app_id:  # A Facebook app ID
  publisher: "https://www.facebook.com/ManoVaikinasVeganas"  # A Facebook page URL or ID of the publishing entity

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.facebook.com/ManoVaikinasVeganas"
    - "https://www.instagram.com/mano_vaikinas_veganas/"

collections:
  receptai:
    output: true
    permalink: /:collection/:path/

include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
